FROM node:22-slim

WORKDIR /app

RUN npm install -g bun

COPY package.json bun.lock* ./

RUN bun install --no-save --frozen-lockfile

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0", "--port", "3000"]
